# src/main/resources/plugin.yml
name: PatrolSpectatorPlugin
main: dev.gonjy.patrolspectator.PatrolSpectatorPlugin
version: ${project.version}
api-version: '1.21'
authors: [ 'gonjy' ]
commands:
  patrol:
    description: 観光巡りコマンド
    usage: /patrol <start|stop|status|rank>
    permission: patrolspectator.use
  bounty:
    description: 賞金首コマンド
    usage: /bounty <info|claim>
    permission: patrol.bounty.use
  stats:
    description: 自分の統計情報と進捗を表示します
    usage: /stats
permissions:
  patrolspectator.use:
    default: op
  patrolspectator.exempt:
    default: false
